#!/usr/bin/env php
<?php

use Arpon\Console\Input\ArgvInput;
use Arpon\Foundation\Application;


// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);